services:
  servicephp-fpm:
    container_name: php-service
    build:
      context: ./
      dockerfile: ./.docker/dockerf-php/Dockerfile
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=servicemysql
      - DB_PORT=3306
      - DB_DATABASE=baseDatosMysql
      - DB_USERNAME=user
      - DB_PASSWORD=1234
      - QUEUE_CONNECTION=redis
      - REDIS_QUEUE_CONNECTION=default
      - REDIS_QUEUE=notifications
    ports: 
      - "${DOCKER_PHP_PORT}:80"
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
      - ./.docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    networks:
      - ${DOCKER_NETWORK}
  servicecomposer:
    container_name: composer-service
    build:
      context: ./
      dockerfile: ./.docker/dockerf-composer/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - ${DOCKER_NETWORK}
  servicemysql:
    container_name: mysql-service
    build:
      context: ./
      dockerfile: ./.docker/dockerf-mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    volumes:
      - ./.docker/volumes/mysql-data:/var/lib/mysql
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    user: "999:1001"
    networks:
      - ${DOCKER_NETWORK}
  serviceredis:
    container_name: redis-service
    image: redis:latest
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    networks:
      - ${DOCKER_NETWORK}
  servicephpmyadmin:
    container_name: phpmyadmin-service
    image: phpmyadmin:latest
    environment:
      PMA_HOST: servicemysql
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    networks:
       - ${DOCKER_NETWORK}
  servicemailpit:
    container_name: mailpit
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
       - ${DOCKER_NETWORK}

networks:
    red-app:

