name: Deploy Tickets-project to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_location: false
          script: |
            cd ${{ secrets.VPS_DIR }}
            git pull origin main
            
            # Dependencias de PHP
            composer install --no-dev --optimize-autoloader --no-interaction
            
            # Instalar dependencias de JS y compilar (Vite)
            /opt/plesk/php/8.4/npm install
            /opt/plesk/php/8.4/npm run build
            
            # Migraciones y cach√© de laravel para rendimiento
            /opt/plesk/php/8.4/php artisan migrate --force
            /opt/plesk/php/8.4/php artisan optimize
            /opt/plesk/php/8.4/php artisan view:cache
            /opt/plesk/php/8.4/php artisan event:cache
            
            # Permisos de directorios
            /opt/plesk/php/8.4/chown -R www-data:www-data storage bootstrap/cache
            /opt/plesk/php/8.4/chmod -R 775 storage bootstrap/cache