name: Deploy Tickets-project to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy using Rsync
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -av --delete
          path: ./src/
          remote_path: ${{ secrets.VPS_DIR }}
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}
          remote_port: ${{ secrets.VPS_PORT }}

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.VPS_DIR }}
            
            # Dependencias de PHP
            /opt/plesk/php/8.4/bin/php /usr/bin/composer install --no-dev --optimize-autoloader --no-interaction
            
            # Instalar dependencias de JS y compilar (Vite)
            npm install
            npm run build
            
            # Migraciones y cach√© de laravel para rendimiento
            /opt/plesk/php/8.4/bin/php artisan migrate --force
            /opt/plesk/php/8.4/bin/php artisan optimize
            /opt/plesk/php/8.4/bin/php artisan view:cache
            /opt/plesk/php/8.4/bin/php artisan event:cache
            
            # Permisos de directorios
            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache